import type { MarketContract } from '../types/market.types';
import { generateSparkline } from '../utils/mockUtils';

export const seedMarkets: MarketContract[] = [
  {
    id: 'm-polymarket-hormuz',
    questionText: 'Will Iran close the Strait of Hormuz in 2026?',
    title: 'Strait of Hormuz Closure',
    platform: 'polymarket',
    probability: 61.5,
    probability24hAgo: 45.0,
    change24h: 16.5, // Significant event
    delta: 1.2,
    volume: 12500000,
    category: 'geopolitics',
    sentimentScore: 73.3,
    sentimentDelta: 11.8,
    expiresAt: new Date('2026-12-31T23:59:59Z').toISOString(),
    timestamp: new Date().toISOString(),
    linkedTrendIds: ['t-hormuz-tension'],
    priceHistory: [],
    sparklineData: generateSparkline(48, 40, 65, 61.5),
  },
  {
    id: 'm-kalshi-fed-q2',
    questionText: 'Will the Fed cut the target rate range below 4.5% in Q2?',
    title: 'Fed Rate Cut Q2',
    platform: 'kalshi',
    probability: 74.0,
    probability24hAgo: 76.5,
    change24h: -2.5,
    delta: -0.5,
    volume: 4500000,
    category: 'economics',
    sentimentScore: 72.8,
    sentimentDelta: -1.2,
    expiresAt: new Date('2026-06-30T23:59:59Z').toISOString(),
    timestamp: new Date().toISOString(),
    linkedTrendIds: ['t-fed-pivot'],
    priceHistory: [],
    sparklineData: generateSparkline(48, 70, 80, 74.0),
  },
  {
    id: 'm-polymarket-tsmc',
    questionText: 'Will TSMC delay production at Arizona Fab 2 to 2027?',
    title: 'TSMC Arizona Delay',
    platform: 'polymarket',
    probability: 35.0,
    probability24hAgo: 38.0,
    change24h: -3.0,
    delta: -1.0,
    volume: 1200000,
    category: 'technology',
    sentimentScore: 28.5,
    sentimentDelta: -6.5,
    expiresAt: new Date('2026-06-30T23:59:59Z').toISOString(),
    timestamp: new Date().toISOString(),
    linkedTrendIds: ['t-chip-supply'],
    priceHistory: [],
    sparklineData: generateSparkline(48, 30, 45, 35.0),
  },
  {
    id: 'm-polymarket-gpt5',
    questionText: 'Will OpenAI release GPT-5 before Oct 2026?',
    title: 'GPT-5 by October',
    platform: 'polymarket',
    probability: 82.0,
    probability24hAgo: 79.5,
    change24h: 2.5,
    delta: 1.5,
    volume: 8500000,
    category: 'technology',
    sentimentScore: 87.5,
    sentimentDelta: 5.5,
    expiresAt: new Date('2026-09-30T23:59:59Z').toISOString(),
    timestamp: new Date().toISOString(),
    linkedTrendIds: ['t-agi-timeline'],
    priceHistory: [],
    sparklineData: generateSparkline(48, 75, 85, 82.0),
  }
];
