import type { SentimentQuestion } from '../types/sentiment.types';
import { generateSparkline } from '../utils/mockUtils';

export const seedQuestions: SentimentQuestion[] = [
  {
    id: 'q-iran-strait-2026',
    text: 'Will Iran close the Strait of Hormuz before July 2026?',
    category: 'geopolitics',
    yesCount: 4205,
    noCount: 1530,
    score: 73.3,
    confidence: 0.88,
    confidenceLevel: 'high',
    direction: 'rising',
    marketProbability: 61.5,
    marketDelta: 11.8,
    tweetVolume: 5735,
    stanceBreakdown: { yes: 4205, no: 1530, neutral: 840, ambiguous: 310 },
    sparklineData: generateSparkline(48, 65, 80, 73.3), // 24h history
    timestamp: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    linkedTrendIds: ['t-hormuz-tension'],
    linkedMarketIds: ['m-polymarket-hormuz'],
  },
  {
    id: 'q-fed-cuts-q2',
    text: 'Will the Fed cut rates in Q2 2026?',
    category: 'economics',
    yesCount: 12050,
    noCount: 4500,
    score: 72.8,
    confidence: 0.92,
    confidenceLevel: 'high',
    direction: 'stable',
    marketProbability: 74.0,
    marketDelta: -1.2,
    tweetVolume: 16550,
    stanceBreakdown: { yes: 12050, no: 4500, neutral: 3200, ambiguous: 1100 },
    sparklineData: generateSparkline(48, 60, 75, 72.8),
    timestamp: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    linkedTrendIds: ['t-fed-pivot'],
    linkedMarketIds: ['m-kalshi-fed-q2'],
  },
  {
    id: 'q-tsmc-delay',
    text: 'Will TSMC delay Arizona Fab 2 production to 2027?',
    category: 'technology',
    yesCount: 840,
    noCount: 2100,
    score: 28.5,
    confidence: 0.75,
    confidenceLevel: 'medium',
    direction: 'falling',
    marketProbability: 35.0,
    marketDelta: -6.5,
    tweetVolume: 2940,
    stanceBreakdown: { yes: 840, no: 2100, neutral: 500, ambiguous: 120 },
    sparklineData: generateSparkline(48, 20, 40, 28.5),
    timestamp: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    linkedTrendIds: ['t-chip-supply'],
    linkedMarketIds: ['m-polymarket-tsmc'],
  },
  {
    id: 'q-trump-tariffs-eu',
    text: 'Will Trump impose >25% tariffs on EU goods before end of 2026?',
    category: 'geopolitics',
    yesCount: 3800,
    noCount: 3100,
    score: 55.0,
    confidence: 0.65,
    confidenceLevel: 'medium',
    direction: 'rising',
    marketProbability: 48.5,
    marketDelta: 6.5,
    tweetVolume: 6900,
    stanceBreakdown: { yes: 3800, no: 3100, neutral: 2100, ambiguous: 850 },
    sparklineData: generateSparkline(48, 45, 60, 55.0),
    timestamp: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    linkedTrendIds: ['t-eu-trade-war'],
    linkedMarketIds: [],
  },
  {
    id: 'q-openai-gpt5',
    text: 'Will OpenAI release GPT-5 before Oct 2026?',
    category: 'technology',
    yesCount: 15400,
    noCount: 2200,
    score: 87.5,
    confidence: 0.95,
    confidenceLevel: 'high',
    direction: 'stable',
    marketProbability: 82.0,
    marketDelta: 5.5,
    tweetVolume: 17600,
    stanceBreakdown: { yes: 15400, no: 2200, neutral: 4500, ambiguous: 1200 },
    sparklineData: generateSparkline(48, 75, 95, 87.5),
    timestamp: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    linkedTrendIds: ['t-agi-timeline'],
    linkedMarketIds: ['m-polymarket-gpt5'],
  }
];
