import type { TrendLifecycle, Category } from '@/types'

export interface SeedTrend {
  id: string
  hashtag: string
  name: string
  category: Category
  lifecycle: TrendLifecycle
  velocity: number
  velocityDelta: number
  eventCount: number
  linkedMarketIds: string[]
  topEntityIds: string[]
}

export const seedTrends: SeedTrend[] = [
  // ─── Emerging (3) ──────────────────────────────────────
  {
    id: 'trend-013',
    hashtag: '#NKMissileAlert',
    name: 'North Korea Missile Alert',
    category: 'geopolitics',
    lifecycle: 'emerging',
    velocity: 28,
    velocityDelta: 12.4,
    eventCount: 34,
    linkedMarketIds: ['mkt-019'],
    topEntityIds: ['ent-029'],
  },
  {
    id: 'trend-014',
    hashtag: '#WinterOlympics2026',
    name: 'Winter Olympics 2026',
    category: 'sports',
    lifecycle: 'emerging',
    velocity: 22,
    velocityDelta: 8.1,
    eventCount: 19,
    linkedMarketIds: ['mkt-018'],
    topEntityIds: ['ent-025'],
  },
  {
    id: 'trend-015',
    hashtag: '#UCLFinal',
    name: 'Champions League Final',
    category: 'sports',
    lifecycle: 'emerging',
    velocity: 18,
    velocityDelta: 5.3,
    eventCount: 12,
    linkedMarketIds: ['mkt-021'],
    topEntityIds: ['ent-030'],
  },

  // ─── Trending (5) ──────────────────────────────────────
  {
    id: 'trend-001',
    hashtag: '#IranStraitCrisis',
    name: 'Iran Strait of Hormuz Crisis',
    category: 'geopolitics',
    lifecycle: 'trending',
    velocity: 72,
    velocityDelta: 8.3,
    eventCount: 245,
    linkedMarketIds: ['mkt-001', 'mkt-002', 'mkt-025'],
    topEntityIds: ['ent-021', 'ent-031', 'ent-011', 'ent-006', 'ent-041'],
  },
  {
    id: 'trend-003',
    hashtag: '#FedRateWatch',
    name: 'Federal Reserve Rate Decision',
    category: 'economics',
    lifecycle: 'trending',
    velocity: 65,
    velocityDelta: 4.2,
    eventCount: 189,
    linkedMarketIds: ['mkt-005', 'mkt-006', 'mkt-016'],
    topEntityIds: ['ent-002', 'ent-012', 'ent-044', 'ent-042'],
  },
  {
    id: 'trend-006',
    hashtag: '#UkraineCeasefire',
    name: 'Ukraine Ceasefire Negotiations',
    category: 'geopolitics',
    lifecycle: 'trending',
    velocity: 58,
    velocityDelta: -2.1,
    eventCount: 312,
    linkedMarketIds: ['mkt-009', 'mkt-010', 'mkt-020'],
    topEntityIds: ['ent-004', 'ent-005', 'ent-013', 'ent-024', 'ent-023'],
  },
  {
    id: 'trend-008',
    hashtag: '#GPT5Rumors',
    name: 'GPT-5 Release Speculation',
    category: 'technology',
    lifecycle: 'trending',
    velocity: 52,
    velocityDelta: 15.6,
    eventCount: 156,
    linkedMarketIds: ['mkt-013', 'mkt-024'],
    topEntityIds: ['ent-008', 'ent-015', 'ent-036'],
  },
  {
    id: 'trend-011',
    hashtag: '#CryptoRegulation',
    name: 'Cryptocurrency Regulation',
    category: 'technology',
    lifecycle: 'trending',
    velocity: 44,
    velocityDelta: 2.8,
    eventCount: 98,
    linkedMarketIds: ['mkt-012'],
    topEntityIds: ['ent-020', 'ent-016', 'ent-017', 'ent-043'],
  },

  // ─── Peaking (4) ───────────────────────────────────────
  {
    id: 'trend-002',
    hashtag: '#TrumpTariffEscalation',
    name: 'Trump Tariff Escalation',
    category: 'economics',
    lifecycle: 'peaking',
    velocity: 88,
    velocityDelta: -1.4,
    eventCount: 420,
    linkedMarketIds: ['mkt-003', 'mkt-004', 'mkt-022'],
    topEntityIds: ['ent-001', 'ent-025', 'ent-030', 'ent-022'],
  },
  {
    id: 'trend-005',
    hashtag: '#TaiwanStrait',
    name: 'Taiwan Strait Tensions',
    category: 'geopolitics',
    lifecycle: 'peaking',
    velocity: 78,
    velocityDelta: -0.8,
    eventCount: 267,
    linkedMarketIds: ['mkt-008', 'mkt-017'],
    topEntityIds: ['ent-003', 'ent-022', 'ent-026', 'ent-032', 'ent-046'],
  },
  {
    id: 'trend-007',
    hashtag: '#TeslaRally',
    name: 'Tesla Stock Rally',
    category: 'technology',
    lifecycle: 'peaking',
    velocity: 61,
    velocityDelta: -3.5,
    eventCount: 178,
    linkedMarketIds: ['mkt-011'],
    topEntityIds: ['ent-007', 'ent-050'],
  },
  {
    id: 'trend-010',
    hashtag: '#IndiaDemographics',
    name: 'India Demographic Shift',
    category: 'culture',
    lifecycle: 'peaking',
    velocity: 35,
    velocityDelta: -0.5,
    eventCount: 45,
    linkedMarketIds: ['mkt-015'],
    topEntityIds: ['ent-010', 'ent-027'],
  },

  // ─── Cooling (3) ───────────────────────────────────────
  {
    id: 'trend-004',
    hashtag: '#USChinaTrade',
    name: 'US-China Trade War',
    category: 'economics',
    lifecycle: 'cooling',
    velocity: 25,
    velocityDelta: -8.2,
    eventCount: 380,
    linkedMarketIds: ['mkt-007', 'mkt-023'],
    topEntityIds: ['ent-001', 'ent-003', 'ent-022', 'ent-025', 'ent-049'],
  },
  {
    id: 'trend-009',
    hashtag: '#ECBPolicy',
    name: 'ECB Monetary Policy',
    category: 'economics',
    lifecycle: 'cooling',
    velocity: 20,
    velocityDelta: -5.6,
    eventCount: 120,
    linkedMarketIds: ['mkt-014'],
    topEntityIds: ['ent-009', 'ent-014', 'ent-048'],
  },
  {
    id: 'trend-012',
    hashtag: '#EUTradeTalks',
    name: 'EU Trade Negotiations',
    category: 'economics',
    lifecycle: 'cooling',
    velocity: 15,
    velocityDelta: -4.1,
    eventCount: 87,
    linkedMarketIds: ['mkt-022'],
    topEntityIds: ['ent-030', 'ent-038'],
  },
]
